/* ═══ PORTFOLIO CHANGES — old (April 2026 site) → new (July 2026), per Brian's change tables ═══
   status: kept | swap | add. l = layer index matching PORTFOLIOS layer order. */
const CHANGES = {
  def: [
    { l: 0, old: { t: "VTI", opt: "SCHB", w: 9 },  nw: { t: "VTI", opt: "SCHB", w: 8 },  status: "kept" },
    { l: 0, old: { t: "IBIT", opt: "BTC", w: 6 },  nw: { t: "IBIT", opt: "BTC", w: 7 },  status: "kept" },
    { l: 0, old: { t: "VXUS", opt: "IXUS", w: 10 },nw: { t: "VXUS", opt: "IXUS", w: 9 }, status: "kept" },
    { l: 0, old: { t: "GLDM", opt: "GLD", w: 6 },  nw: { t: "GLDM", opt: "GLD", w: 4 },  status: "kept" },
    { l: 0, old: { t: "VOO", opt: "QQQM", w: 5 },  nw: { t: "VOO", opt: "QQQM", w: 4 },  status: "kept" },
    { l: 0, old: { t: "SCHD", opt: "VYM", w: 5 },  nw: { t: "SCHD", opt: "VYM", w: 6 },  status: "kept" },
    { l: 1, old: { t: "AIPO", opt: "SMH", w: 4 },  nw: { t: "AIPO", opt: "POWR", w: 4 }, status: "kept" },
    { l: 1, old: { t: "NLR", opt: "NUKZ", w: 3 },  nw: { t: "AIRR", opt: "VOLT", w: 3 }, status: "swap" },
    { l: 1, old: { t: "SHLD", opt: "DRNZ", w: 5 }, nw: { t: "SHLD", opt: "XLI", w: 4 },  status: "kept" },
    { l: 1, old: { t: "CIBR", opt: "ROBT", w: 2 }, nw: { t: "IGV", opt: "ROBT", w: 3 },  status: "swap" },
    { l: 1, old: { t: "DRAM", opt: "SMH", w: 3 },  nw: { t: "DRAM", opt: "TCAI", w: 4 }, status: "kept" },
    { l: 1, old: { t: "SLV", opt: "COPX", w: 4 },  nw: { t: "COPX", opt: "REMX", w: 3 }, status: "swap" },
    { l: 1, old: { t: "TCAI", opt: "AIQ", w: 3 },  nw: { t: "EUV", opt: "SOXX", w: 2 },  status: "swap" },
    { l: 2, old: { t: "MU", opt: "GLW", w: 4 },    nw: { t: "MU", opt: "SKHY", w: 4 },   status: "kept" },
    { l: 2, old: { t: "AMZN", opt: "GOOG", w: 3 }, nw: { t: "MSFT", opt: "NVDA", w: 3 }, status: "swap" },
    { l: 2, old: { t: "MRVL", opt: "GLW", w: 4 },  nw: { t: "MRVL", opt: "GLW", w: 3 },  status: "kept" },
    { l: 2, old: { t: "VRT", opt: "GEV", w: 3 },   nw: { t: "LNG", opt: "WMB", w: 3 },   status: "swap" },
    { l: 2, old: { t: "NOW", opt: "HOOD", w: 2 },  nw: { t: "NOW", opt: "HOOD", w: 3 },  status: "kept" },
    { l: 2, old: { t: "PLTR", opt: "TSLA", w: 3 }, nw: { t: "PLTR", opt: "TSLA", w: 3 }, status: "kept" },
    { l: 2, old: { t: "ETN", opt: "VST", w: 3 },   nw: { t: "ETN", opt: "VST", w: 3 },   status: "kept" },
    { l: 2, old: { t: "LLY", opt: "HIMS", w: 3 },  nw: { t: "LLY", opt: "HIMS", w: 2 },  status: "kept" },
    { l: 2, old: null,                             nw: { t: "RBRK", opt: "MDB", w: 3 },  status: "add" },
    { l: 3, old: { t: "RKLB", opt: "ASTS", w: 3 }, nw: { t: "RKLB", opt: "ASTS", w: 3 }, status: "kept" },
    { l: 3, old: { t: "NBIS", opt: "IREN", w: 3 }, nw: { t: "NBIS", opt: "IREN/CRWV", w: 2 }, status: "kept" },
    { l: 3, old: { t: "VPG", opt: "ONDS", w: 2 },  nw: { t: "VPG", opt: "PENG", w: 3 },  status: "kept" },
    { l: 3, old: { t: "BE", opt: "FLNC", w: 2 },   nw: { t: "BE", opt: "FLNC/FCEL", w: 2 }, status: "kept" },
    { l: 2, old: null,                             nw: { t: "HOOD", opt: "ZETA", w: 2 }, status: "add" }
  ],
  agg: [
    { l: 0, old: { t: "VTI", opt: "SCHB", w: 8 },  nw: { t: "VTI", opt: "SCHB", w: 7 },  status: "kept" },
    { l: 0, old: { t: "IBIT", opt: "BTC", w: 7 },  nw: { t: "IBIT", opt: "BTC", w: 8 },  status: "kept" },
    { l: 0, old: { t: "VXUS", opt: "IXUS", w: 7 }, nw: { t: "VXUS", opt: "IXUS", w: 6 }, status: "kept" },
    { l: 0, old: { t: "GLDM", opt: "GLD", w: 4 },  nw: { t: "COPX", opt: "GLD", w: 4 },  status: "swap" },
    { l: 0, old: { t: "QQQM", opt: "VOO", w: 4 },  nw: { t: "QQQM", opt: "VOO", w: 4 },  status: "kept" },
    { l: 0, old: { t: "SCHD", opt: "VYM", w: 6 },  nw: { t: "SCHD", opt: "VYM", w: 6 },  status: "kept" },
    { l: 1, old: { t: "AIPO", opt: "SMH", w: 4 },  nw: { t: "AIPO", opt: "POWR", w: 3 }, status: "kept" },
    { l: 1, old: { t: "SMH", opt: "AIQ", w: 3 },   nw: { t: "SMH", opt: "AIQ", w: 3 },  status: "kept" },
    { l: 1, old: { t: "NLR", opt: "NUKZ", w: 4 },  nw: { t: "AIRR", opt: "XLI", w: 3 }, status: "swap" },
    { l: 1, old: { t: "SHLD", opt: "DRNZ", w: 3 }, nw: { t: "IGV", opt: "CIBR", w: 3 },  status: "swap" },
    { l: 1, old: { t: "CIBR", opt: "ROBT", w: 3 }, nw: { t: "ROBO", opt: "ROBT", w: 3 }, status: "swap" },
    { l: 1, old: { t: "DRAM", opt: "TCAI", w: 3 }, nw: { t: "DRAM", opt: "TCAI", w: 3 }, status: "kept" },
    { l: 1, old: { t: "COPX", opt: "SLV", w: 3 },  nw: { t: "COPX", opt: "REMX", w: 4 }, status: "kept" },
    { l: 1, old: null,                             nw: { t: "EUV", opt: "TCAI", w: 2 },  status: "add" },
    { l: 2, old: { t: "MU", opt: "GLW", w: 5 },    nw: { t: "MU", opt: "SKHY", w: 4 },   status: "kept" },
    { l: 2, old: { t: "AMZN", opt: "GOOG", w: 4 }, nw: { t: "PLTR", opt: "IGV", w: 4 },  status: "swap" },
    { l: 2, old: { t: "MRVL", opt: "GLW", w: 5 },  nw: { t: "MRVL", opt: "ARM", w: 4 },  status: "kept" },
    { l: 2, old: { t: "ETN", opt: "VRT", w: 4 },   nw: { t: "LNG", opt: "WMB", w: 2 },   status: "swap" },
    { l: 2, old: { t: "NOW", opt: "GOOG", w: 3 },  nw: { t: "NOW", opt: "HOOD", w: 3 },  status: "kept" },
    { l: 2, old: { t: "TSLA", opt: "PLTR", w: 4 }, nw: { t: "VPG", opt: "TSLA", w: 3 },  status: "swap" },
    { l: 2, old: { t: "RKLB", opt: "ASTS", w: 3 }, nw: { t: "RKLB", opt: "ASTS", w: 4 }, status: "kept" },
    { l: 2, old: { t: "LLY", opt: "SOFI", w: 2 },  nw: { t: "HIMS", opt: "LLY", w: 2 },  status: "swap" },
    { l: 2, old: null,                             nw: { t: "RBRK", opt: "MDB", w: 2 },  status: "add" },
    { l: 2, old: null,                             nw: { t: "IBM", opt: "DELL", w: 2 },  status: "add" },
    { l: 3, old: { t: "ASTS", opt: "RKLB", w: 2 }, nw: { t: "VEEV", opt: "TEM", w: 2 },  status: "swap" },
    { l: 3, old: { t: "NBIS", opt: "IREN", w: 3 }, nw: { t: "NBIS", opt: "IREN/CRWV", w: 3 }, status: "kept" },
    { l: 3, old: { t: "HIMS", opt: "OUST", w: 2 }, nw: { t: "PENG", opt: "OUST", w: 2 }, status: "swap" },
    { l: 3, old: { t: "BE", opt: "FLNC", w: 2 },   nw: { t: "BE", opt: "FLNC/FCEL", w: 2 }, status: "kept" },
    { l: 3, old: { t: "AAOI", opt: "COHR", w: 2 }, nw: { t: "HOOD", opt: "INOD", w: 2 }, status: "swap" }
  ],
  hc: [
    { l: 0, old: { t: "VTI", opt: "SCHB", w: 7 },  nw: { t: "VTI", opt: "SCHB", w: 7 },  status: "kept" },
    { l: 0, old: { t: "IBIT", opt: "BTC", w: 9 },  nw: { t: "IBIT", opt: "BTC", w: 10 }, status: "kept" },
    { l: 0, old: { t: "VXUS", opt: "IXUS", w: 6 }, nw: { t: "VXUS", opt: "IXUS", w: 5 }, status: "kept" },
    { l: 0, old: { t: "GLDM", opt: "GLD", w: 4 },  nw: { t: "COPX", opt: "GLD", w: 4 },  status: "swap" },
    { l: 0, old: { t: "QQQM", opt: "VOO", w: 2 },  nw: { t: "QQQM", opt: "VOO", w: 2 },  status: "kept" },
    { l: 1, old: { t: "AIPO", opt: "SMH", w: 4 },  nw: { t: "AIPO", opt: "POWR", w: 3 }, status: "kept" },
    { l: 1, old: { t: "SMH", opt: "AIQ", w: 3 },   nw: { t: "SMH", opt: "SOXX", w: 3 },   status: "kept" },
    { l: 1, old: { t: "NLR", opt: "NUKZ", w: 4 },  nw: { t: "AIRR", opt: "VOLT", w: 3 }, status: "swap" },
    { l: 1, old: { t: "TCAI", opt: "ROBT", w: 3 }, nw: { t: "TCAI", opt: "ROBT", w: 3 }, status: "kept" },
    { l: 1, old: { t: "DRAM", opt: "CIBR", w: 3 }, nw: { t: "DRAM", opt: "CIBR", w: 3 }, status: "kept" },
    { l: 1, old: { t: "SLV", opt: "COPX", w: 3 },  nw: { t: "REMX", opt: "SLV", w: 4 },  status: "swap" },
    { l: 1, old: null,                             nw: { t: "EUV", opt: "WGMI", w: 2 },  status: "add" },
    { l: 2, old: { t: "AMD", opt: "AVGO", w: 5 },  nw: { t: "IGV", opt: "MELI", w: 4 },  status: "swap" },
    { l: 2, old: { t: "MU", opt: "GLW", w: 4 },    nw: { t: "MU", opt: "SKHY", w: 4 },   status: "kept" },
    { l: 2, old: { t: "PLTR", opt: "INTC", w: 4 }, nw: { t: "PLTR", opt: "IGV", w: 3 },  status: "kept" },
    { l: 2, old: { t: "MRVL", opt: "ARM", w: 4 },  nw: { t: "MRVL", opt: "ARM", w: 4 },  status: "kept" },
    { l: 2, old: { t: "VST", opt: "ETN", w: 3 },   nw: { t: "LNG", opt: "WMB", w: 2 },   status: "swap" },
    { l: 2, old: { t: "AMZN", opt: "GOOG", w: 4 }, nw: { t: "MSFT", opt: "HOOD", w: 3 }, status: "swap" },
    { l: 2, old: { t: "MOD", opt: "BWXT", w: 3 },  nw: { t: "ETN", opt: "VST", w: 2 },   status: "swap" },
    { l: 2, old: { t: "TSLA", opt: "VPG", w: 4 },  nw: { t: "VPG", opt: "TSLA", w: 4 },  status: "kept" },
    { l: 2, old: { t: "TER", opt: "—", w: 2 },     nw: { t: "RBRK", opt: "MDB", w: 3 },  status: "swap" },
    { l: 2, old: { t: "NOW", opt: "HOOD", w: 3 },  nw: { t: "NOW", opt: "HOOD", w: 2 },  status: "kept" },
    { l: 2, old: { t: "LLY", opt: "HIMS", w: 2 },  nw: { t: "HIMS", opt: "LLY", w: 2 },  status: "kept" },
    { l: 2, old: null,                             nw: { t: "DELL", opt: "IBM", w: 2 },  status: "add" },
    { l: 3, old: { t: "RKLB", opt: "ASTS", w: 4 }, nw: { t: "RKLB", opt: "ASTS", w: 4 }, status: "kept" },
    { l: 3, old: { t: "NBIS", opt: "MOD", w: 3 },  nw: { t: "NBIS", opt: "IREN/CRWV", w: 3 }, status: "kept" },
    { l: 3, old: { t: "BE", opt: "FLNC", w: 2 },   nw: { t: "BWEN", opt: "BE/FLNC", w: 2 }, status: "swap" },
    { l: 3, old: { t: "AAOI", opt: "COHR", w: 3 }, nw: { t: "PENG", opt: "OUST", w: 2 }, status: "swap" },
    { l: 3, old: { t: "OKLO", opt: "IONQ", w: 1 }, nw: { t: "FLNC", opt: "FCEL", w: 1 }, status: "swap" },
    { l: 3, old: { t: "ASTS", opt: "LUNR", w: 1 }, nw: { t: "TEM", opt: "VEEV", w: 2 },  status: "swap" },
    { l: 3, old: null,                             nw: { t: "INDI", opt: "INOD", w: 2 }, status: "add" }
  ]
};
